import { faRoad } from '@fortawesome/free-solid-svg-icons'

export { default as Layout } from './layout'
export { default as Header } from './header'
export { default as Footer } from './footer'
export { default as SpeedContact } from './speedContact'
export { default as ProductCard } from './productCard'
export { default as CategoryCard} from './categoryCard'
export { default as Loader } from './loader'
export { default as DetailsPage } from './details'
export { default as InnerHeader } from './innerpagesHeader'
export { default as ContactForm } from './contactForm'
export { default as ContactInfo } from './contactInfo'
export { default as NoData } from './noData'
export { default as FilteredProducts } from './filterProducts'
/* ********** Home components ********/
export { default as Slider } from './homeComponents/slider'
export { default as HomeAbout } from './homeComponents/homeAbout'
export { default as BrandSlider } from './homeComponents/brandSlider'
/* *********** Admin Panel **********/
export { default as AdminLayout } from './adminLayout'
export { default as AdminHeader } from './adminHeader'
export { default as SideMenu } from './sideMenu'
export { default as AdminFooter } from './adminFooter'
export { default as AdminSectionHeader } from './adminSectionHeader'
export { default as AdminTable } from './adminTable'
export { default as AdmenFilterByDelete } from './adminByDelete'
export { default as AdminModal } from './adminModal'
/* *********** Admin Buttons ********/
export { default as EditBtn } from './utilities/editButton'
export { default as DeleteBtn } from './utilities/deleteButton'
export { default as ActiveBtn } from './utilities/activeButton'
/* *********** Forms ***********/
export { default as ConfirmDelete } from './forms/confirmDelete'
export { default as CategoryForm } from './forms/categoryForm'
export { default as BrandForm } from './forms/brandForm'
export { default as UploadImage } from './forms/uploadImage'
export { default as SliderForm } from './forms/sliderForm'
export { default as RolesForm } from './forms/rolesForm'
export { default as UserForm} from './forms/usersForm'
export { default as ProductsForm } from './forms/productForm'
export { default as ChangePasswordForm } from './forms/changePassForm'