export { default as Layout } from './layout'
export { default as Header } from './header'
export { default as Footer } from './footer'
export { default as SpeedContact } from './speedContact'
export { default as ProductCard } from './productCard'
export { default as Loader } from './loader'
export { default as DetailsPage } from './details'
export { default as InnerHeader } from './innerpagesHeader'
export { default as ContactForm } from './contactForm'
export { default as ContactInfo } from './contactInfo'
export { default as NoData } from './noData'
export { default as FilteredProducts } from './filterProducts'
/* ********** Home components ********/
export { default as Slider } from './homeComponents/slider'
export { default as HomeAbout } from './homeComponents/homeAbout'
export { default as BrandSlider } from './homeComponents/brandSlider'
/* *********** Admin Panel **********/
export { default as AdminLayout } from './adminLayout'
export { default as AdminHeader } from './adminHeader'
export { default as SideMenu} from './sideMenu'