export const LangStrings = {
  en : {
    Dir: "ltr",
    websiteTitle: "International Export",
    Home: "Home",
    About: "About",
    Products: "Products",
    Brands: "Brands",
    Contact: "Contact us",
    ReadMore: "Reade More",
    ChangeLang: "Ar",
    EmailUs: "Email us",
    Email: "Please enter valid email",
    Subject: "Message subject",
    Message: "Message",
    Send: "Send",
    ContactInfo: "Contact Information",
    CopyRights: "All Copy Rights are received to International Export 2020",
    LoginHead: "Log in",
    EmailInput: "Please Enter your Email",
    PasswordInput: "Please Enter your password",
    Categories: 'Categories',
    AdBrands: 'Brands',
    AdProducts: 'Products',
    Users: 'Users',
    Add: 'Add New',
    Edit: 'Edit Item',
    Delete: 'Delete Item',
    Cancel: "Cancel",
    Title : "Title",
    ArTitle : "Arabic Title",
    CrDate: "Created Date",
    UpDate: "Updated Date",
    ActiveItem: "Active Items",
    DeleteItem: "Delete Item",
    RestoreItem: "Restore Item",
    All: "All",
    FilterDelete: "Filter Items",
    ConfirmMessage: "Do you really want to delete this item ?",
    EnglishName: 'English Name',
    ArabicName: "Arabic Name"

  }, 
  ar : {
    Dir: "rtl",
    websiteTitle: "إنترناشيونال إكسبورت",
    Home: "الرئيسية",
    About: "حول الشركة",
    Products: "منتجاتنا",
    Brands: "علامات تجارية",
    Contact: "تواصل معنا",
    ReadMore: "المزيد",
    EmailUs: "راسلنا",
    Email: "من فضلك أدخل بريد صحيح",
    Subject: "عنوان الرسالة",
    Message: "الرسالة",
    Send: "أرسل",
    ContactInfo: "معلومات التواصل",
    CopyRights: " جميع الحقوق محفوظة 2020",
    ChangeLang: "En",
    LoginHead: "تسجيل الدخول",
    EmailInput: "البريد الالكتروني",
    PasswordInput: "من فضلك أدخل كلمة المرور",
    Categories: 'التصنيفات',
    AdBrands: 'العلامات التجارية',
    AdProducts: 'المنتجات',
    Users: 'المستخدمين',
    Add: 'إضافة جديد',
    Edit: 'تعديل',
    Delete: 'حذف',
    Title : "عنوان",
    ArTitle : "العنوان العربي",
    CrDate: "تاريخ الانشاء",
    UpDate: "تاريخ التعديل",
    ActiveItem: "العناصر النشطة",
    DeleteItem: "العناصر المحذوفة",
    All: "كل العناصر",
    RestoreItem: "اعادة تنشيط العنصر",
    FilterDelete: "فرز العناصر", 
    ConfirmMessage: "هل أنت متأكد من حذف هذا العنصر ؟",
    EnglishName: 'اسم انجليزي',
    ArabicName: "اسم عربي"
  }
}