export const LangStrings = {
  en : {
    Dir: "ltr",
    websiteTitle: "International Export",
    Home: "Home",
    About: "About",
    Products: "Products",
    Brands: "Brands",
    Contact: "Contact us",
    ReadMore: "Reade More",
    ChangeLang: "Ar",
    EmailUs: "Email us",
    Email: "Please enter valid email",
    Subject: "Message subject",
    Message: "Message",
    Send: "Send",
    ContactInfo: "Contact Information",
    CopyRights: "All Copy Rights are received to International Export 2020"
  }, 
  ar : {
    Dir: "rtl",
    websiteTitle: "إنترناشيونال إكسبورت",
    Home: "الرئيسية",
    About: "حول الشركة",
    Products: "منتجاتنا",
    Brands: "علامات تجارية",
    Contact: "تواصل معنا",
    ReadMore: "المزيد",
    EmailUs: "راسلنا",
    Email: "من فضلك أدخل بريد صحيح",
    Subject: "عنوان الرسالة",
    Message: "الرسالة",
    Send: "أرسل",
    ContactInfo: "معلومات التواصل",
    CopyRights: " جميع الحقوق محفوظة 2020",
    ChangeLang: "En",
  }
}