export const LangStrings = {
  en : {
    Dir: "ltr",
    websiteTitle: "International Export",
    Home: "Home",
    About: "About",
    Products: "Products",
    Brands: "Brands",
    Contact: "Contact us",
    ReadMore: "Reade More",
    ChangeLang: "Ar",
    EmailUs: "Email us",
    Email: "Please enter valid email",
    Subject: "Message subject",
    Message: "Message",
    Send: "Send",
    ContactInfo: "Contact Information",
    CopyRights: "International Export 2020",
    LoginHead: "Log in",
    EmailInput: "Please Enter your Email",
    PasswordInput: "Please Enter your password",
    Categories: 'Categories',
    AdBrands: 'Brands',
    AdProducts: 'Products',
    Users: 'Users',
    Add: 'Add New',
    Edit: 'Edit Item',
    Delete: 'Delete Item',
    Cancel: "Cancel",
    Title : "Title",
    ArTitle : "Arabic Title",
    Description : "Description",
    ArDescription : "Arabic Description",
    Details : "Details",
    ArDetails : "Arabic Details",
    Save:"Save",
    CrDate: "Created Date",
    UpDate: "Updated Date",
    ActiveItem: "Active Items",
    DeleteItem: "Delete Item",
    RestoreItem: "Restore Item",
    All: "All",
    FilterDelete: "Filter Items",
    ConfirmMessage: "Do you really want to delete this item ?",
    EnglishName: 'English Name',
    ArabicName: "Arabic Name",
    Image: 'Picture',
    Slide: 'Main Slide',
    Roles: 'Roles',
    KeyWords: 'Key Words',
    EmailTitle: 'Email',
    UserName:'Username',
    Password: 'Password',
    Phones: 'Phones',
    Address: 'Address',
    ChangePassword: 'Change Password',
    OldPassword: 'Old Password',
    NewPassword: 'New Password',
    CoPassword: 'Confirm Password',

  }, 
  ar : {
    Dir: "rtl",
    websiteTitle: "إنترناشيونال إكسبورت",
    Home: "الرئيسية",
    About: "حول الشركة",
    Products: "منتجاتنا",
    Brands: "علامات تجارية",
    Contact: "تواصل معنا",
    ReadMore: "المزيد",
    EmailUs: "راسلنا",
    Email: "من فضلك أدخل بريد صحيح",
    Subject: "عنوان الرسالة",
    Message: "الرسالة",
    Send: "أرسل",
    ContactInfo: "معلومات التواصل",
    CopyRights: " انترناشيونال اكسبورت 2020",
    ChangeLang: "En",
    LoginHead: "تسجيل الدخول",
    EmailInput: "البريد الالكتروني",
    PasswordInput: "من فضلك أدخل كلمة المرور",
    Categories: 'التصنيفات',
    AdBrands: 'العلامات التجارية',
    AdProducts: 'المنتجات',
    Users: 'المستخدمين',
    Add: 'إضافة جديد',
    Edit: 'تعديل',
    Delete: 'حذف',
    Title : "عنوان",
    ArTitle : "العنوان العربي",
    Description : "الوصف الانجليزي",
    ArDescription : "الوصف العربي",
    Details : "التفاصيل الانجليزي",
    ArDetails : "التفاصيل العربي",
    Save:"Save",
    CrDate: "تاريخ الانشاء",
    UpDate: "تاريخ التعديل",
    ActiveItem: "العناصر النشطة",
    DeleteItem: "العناصر المحذوفة",
    All: "كل العناصر",
    RestoreItem: "اعادة تنشيط العنصر",
    FilterDelete: "فرز العناصر", 
    ConfirmMessage: "هل أنت متأكد من حذف هذا العنصر ؟",
    EnglishName: 'اسم انجليزي',
    ArabicName: "اسم عربي",
    Image: 'اختر صورة ',
    Slide: 'العرض الرئيسي',
    Roles: 'الصلاحيات',
    KeyWords: 'الكلمات الدلالية',
    EmailTitle: 'البريد الالكتروني',
    UserName:'اسم المستخدم',
    Password: 'كلمة المرور',
    Phones: 'التليفونات',
    Address: 'العنوان',
    ChangePassword: 'تغيير كلمة المرور',
    OldPassword: 'كلمة المرور القديمة',
    NewPassword: 'كلمة مرور جديدة',
    CoPassword: 'تأكيد كلمة المرور الجديدة',
  }
}